//------------------------------------------------------------------------------
// <auto-generated>


namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblSosyalMedya
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "hata")]
        public string Ad { get; set; }
        public string Link { get; set; }
        public string ikon { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
